version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcb5_laravel_app
    container_name: mcb5_laravel_app
    restart: unless-stopped
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mcb5_laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mcb5_lara_api
      MYSQL_USER: mcb5_lara_api
      MYSQL_PASSWORD: "mcb5Nanda123#"
      MYSQL_ROOT_PASSWORD: "mcb5Nanda123#"  # optional root password
    ports:
      - "33066:3306"  # map container port 3306 to host port 33066
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
